/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 4 "cloud-broker-c.go"

#include <stdlib.h>
#include <string.h>
#include <stdint.h>

typedef void (*LogFunc)(int level, const char* tag, const char* content);
typedef void (*OnStoppedFunc)(const char* reason);
typedef void (*OnStartedFunc)(const char* region);
typedef void (*OnDeviceIdsFunc)(const char* device_ids_csv);
typedef void (*OnDataFunc)(const char* device_id, const unsigned char* data, int len);
typedef void (*OnConnectedFunc)(const char* device_id, int conn_type);
typedef void (*OnDisconnectedFunc)(const char* device_id, const char* reason);

static inline void callLog(LogFunc f, int level, const char* tag, const char* content) {
    if (f) { f(level, tag, content); }
}
static inline void callOnStopped(OnStoppedFunc f, const char* reason) {
    if (f) { f(reason); }
}
static inline void callOnStarted(OnStartedFunc f, const char* region) {
    if (f) { f(region); }
}
static inline void callOnDeviceIds(OnDeviceIdsFunc f, const char* csv) {
    if (f) { f(csv); }
}
static inline void callOnData(OnDataFunc f, const char* device_id, const unsigned char* data, int len) {
    if (f) { f(device_id, data, len); }
}
static inline void callOnConnected(OnConnectedFunc f, const char* device_id, int conn_type) {
    if (f) { f(device_id, conn_type); }
}
static inline void callOnDisconnected(OnDisconnectedFunc f, const char* device_id, const char* reason) {
    if (f) { f(device_id, reason); }
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void InitSDK(LogFunc log, OnStoppedFunc stopped, OnDeviceIdsFunc deviceIds, OnDataFunc data, OnConnectedFunc connected, OnDisconnectedFunc disconnected, OnStartedFunc started);
extern int StartSDK(char* deviceId, char* token, int tokenType, char** urls, int urlCount);
extern void StopSDK(void);
extern int SendDataSDK(char* deviceId, uint8_t* data, int length);
extern int ConnectSDK(char* deviceId);
extern void DisconnectSDK(char* deviceId);

#ifdef __cplusplus
}
#endif
